name: Publish Release

on:
  push:
    branches: [next]

permissions:
  contents: write

concurrency:
  group: publish-release
  cancel-in-progress: false

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-24.04

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Publish release when current commit is a release
        run: make publish-release
