name: Validate

on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache dev dependencies
        uses: actions/cache@v5
        with:
          path: ./.tmp
          key: ${{ runner.os }}-dependencies-${{ hashFiles('./Makefile') }}

      - name: Lint with shellcheck
        run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache dev dependencies
        uses: actions/cache@v5
        with:
          path: ./.tmp
          key: ${{ runner.os }}-dependencies-${{ hashFiles('./Makefile') }}

      - name: Run tests with sharness
        run: make test
